### ISSUE TITLE
Pink Material

### ISSUE THREAD

**Issue by Leoparodo** [zigurous/unity-cc0textures-importer#1]
When I use this I get a pink material instead of a working one I am using the latest version of everything and using URP

**Comment by adamgraham** [comment]
I'm guessing this problem might be due to URP. I haven't done any specific testing for URP or HDRP, so I may need to add additional support for those render pipelines. I'm going to test further and hopefully provide a fix. A pink (magenta) material is usually caused from an error in the shader, which is why I suspect it's a render pipeline issue.

**Comment by adamgraham** [comment]
For the time being, you can fix this problem by simply changing the shader on the imported materials to whichever URP shader you want to use. The `Universal Render Pipeline/Lit` seems to be the default shader. You can also provide a material to the `Material Prefab` property in the tool itself. This will clone that material when importing new ones.

**Comment by adamgraham** [comment]
As of version 1.2.0, new materials use the default render pipeline shader if no material preset has been selected.
